### ISSUE TITLE
state of the project

### ISSUE THREAD

**Issue by cjaburto** [Prajithp/p5-Google-Cloud-Speech#1]
hello, is this working today?.
if it is, are you supporting the project long term?
thanks in advance.

**Comment by Bruce-57** [comment]
Hello
This module has been very useful for a few years in an application of ours at a financial services company.
I was deploying it on a new project today and discovered it has not kept up with the changes to some of its dependencies. Here are some of the errors:
Mojo::Transaction::success is DEPRECATED in favor of Mojo::Transaction::result and Mojo::Transaction::error at /root/perl5/lib/perl5/Google/Cloud/Speech/Auth.pm line 45.

Mojo::Transaction::success is DEPRECATED in favor of Mojo::Transaction::result and Mojo::Transaction::error at /root/perl5/lib/perl5/Google/Cloud/Speech.pm line 129.

IO::Socket::SSL 2.009+ required for TLS support at /root/perl5/lib/perl5/Google/Cloud/Speech/Auth.pm line 45.

I worked around these but I am wondering if you will be doing any updates please?

Thank you in advance!

**Comment by Prajithp** [comment]
@Bruce-57 It would be great if you can send a Pull request.

**Comment by Prajithp** [comment]
@ytnobody Thanks for the PR :) Just made a cpan release now.
